/**
 * This module manages the pool of words used in the game and provides functionality to pick random
 * words for each round. It also includes logic to filter out recently used words to enhance game variety
 * and prevent repeats. The word pool can be easily extended in the future to support different categories
 * and difficulty levels.
 */

import { GAME_CONSTANTS } from '@scribblitz/shared';

const DEFAULT_WORDS = [
  'ace',
  'ant',
  'arm',
  'ash',
  'axe',
  'bad',
  'bag',
  'bar',
  'bat',
  'bed',
  'bee',
  'BMW',
  'BMX',
  'bow',
  'box',
  'boy',
  'bus',
  'can',
  'cap',
  'cat',
  'cow',
  'cup',
  'cut',
  'day',
  'dew',
  'die',
  'dig',
  'DNA',
  'dog',
  'ear',
  'eat',
  'eel',
  'egg',
  'emu',
  'end',
  'eye',
  'flu',
  'fly',
  'fog',
  'fox',
  'fur',
  'gas',
  'gem',
  'God',
  'Gru',
  'ham',
  'hat',
  'hen',
  'hop',
  'hot',
  'hug',
  'hut',
  'ice',
  'ivy',
  'jaw',
  'keg',
  'key',
  'KFC',
  'lap',
  'lid',
  'log',
  'low',
  'map',
  'mop',
  'MTV',
  'mud',
  'mug',
  'nun',
  'nut',
  'oar',
  'oil',
  'old',
  'owl',
  'pan',
  'paw',
  'pie',
  'pig',
  'pin',
  'pot',
  'pro',
  'pub',
  'ram',
  'rat',
  'red',
  'rib',
  'rug',
  'run',
  'sad',
  'sea',
  'sew',
  'shy',
  'sit',
  'ski',
  'sky',
  'son',
  'spy',
  'sun',
  'tea',
  'tie',
  'tip',
  'toe',
  'toy',
  'tug',
  'UFO',
  'USB',
  'wax',
  'web',
  'wig',
  'zoo',
  'ABBA',
  'acid',
  'acne',
  'afro',
  'arch',
  'Asia',
  'atom',
  'Audi',
  'baby',
  'bait',
  'bald',
  'ball',
  'bank',
  'bark',
  'barn',
  'base',
  'beak',
  'bean',
  'bear',
  'beef',
  'beer',
  'beet',
  'bell',
  'belt',
  'bill',
  'bird',
  'bite',
  'blue',
  'boar',
  'boat',
  'boil',
  'bomb',
  'book',
  'bowl',
  'bull',
  'burp',
  'cage',
  'cake',
  'cape',
  'cash',
  'cast',
  'cave',
  'cell',
  'chef',
  'chew',
  'chin',
  'clap',
  'claw',
  'clay',
  'coal',
  'coat',
  'coin',
  'cola',
  'cold',
  'comb',
  'cone',
  'copy',
  'cord',
  'cork',
  'corn',
  'crab',
  'crow',
  'Cuba',
  'cube',
  'cute',
  'dead',
  'deaf',
  'deep',
  'deer',
  'dent',
  'derp',
  'desk',
  'dice',
  'diet',
  'diva',
  'dock',
  'doll',
  'dome',
  'door',
  'Dora',
  'dots',
  'drip',
  'drum',
  'duck',
  'duel',
  'east',
  'echo',
  'Elmo',
  'Elsa',
  'exam',
  'face',
  'fall',
  'farm',
  'fast',
  'fern',
  'Finn',
  'fish',
  'fizz',
  'flag',
  'flea',
  'foil',
  'food',
  'fork',
  'fort',
  'frog',
  'full',
  'gang',
  'gasp',
  'gate',
  'germ',
  'gift',
  'girl',
  'glow',
  'glue',
  'goal',
  'goat',
  'gold',
  'golf',
  'good',
  'grid',
  'grin',
  'hair',
  'half',
  'halo',
  'hand',
  'hard',
  'harp',
  'head',
  'heat',
  'heel',
  'hell',
  'hero',
  'hill',
  'hive',
  'hoof',
  'hook',
  'horn',
  'hose',
  'Hulk',
  'hurt',
  'idea',
  'Ikea',
  'iPad',
  'iron',
  'jail',
  'JayZ',
  'jazz',
  'jeep',
  'king',
  'kiss',
  'kite',
  'kiwi',
  'knee',
  'knot',
  'lady',
  'lake',
  'lamb',
  'lamp',
  'lane',
  'lava',
  'leaf',
  'leak',
  'Lego',
  'legs',
  'lens',
  'lily',
  'lime',
  'line',
  'link',
  'lion',
  'lips',
  'loaf',
  'lock',
  'logo',
  'loot',
  'love',
  'luck',
  'lung',
  'lynx',
  'maid',
  'mall',
  'Mars',
  'mask',
  'maze',
  'meal',
  'meat',
  'melt',
  'meme',
  'milk',
  'mime',
  'mint',
  'mold',
  'mole',
  'monk',
  'moon',
  'moss',
  'moth',
  'nail',
  'Nasa',
  'navy',
  'neck',
  'Nemo',
  'nerd',
  'nest',
  'Nike',
  'noob',
  'nose',
  'nuke',
  'Olaf',
  'open',
  'orca',
  'Oreo',
  'oval',
  'page',
  'pain',
  'palm',
  'park',
  'path',
  'pear',
  'peas',
  'pike',
  'pill',
  'pine',
  'pink',
  'pipe',
  'plow',
  'plug',
  'poke',
  'polo',
  'pond',
  'pony',
  'poop',
  'poor',
  'pope',
  'pray',
  'puma',
  'punk',
  'race',
  'raft',
  'rail',
  'rain',
  'rake',
  'ramp',
  'read',
  'rest',
  'rice',
  'Rick',
  'ring',
  'risk',
  'rock',
  'roll',
  'Rome',
  'roof',
  'room',
  'root',
  'rose',
  'ruby',
  'rune',
  'safe',
  'sale',
  'salt',
  'sand',
  'scar',
  'seal',
  'seed',
  'shoe',
  'shop',
  'sick',
  'silo',
  'sing',
  'sink',
  'skin',
  'slam',
  'slow',
  'snow',
  'soap',
  'soda',
  'soil',
  'soup',
  'spin',
  'spit',
  'stab',
  'star',
  'step',
  'swag',
  'swan',
  'taco',
  'tail',
  'tank',
  'tape',
  'taxi',
  'tear',
  'tent',
  'text',
  'thin',
  'Thor',
  'thug',
  'tiny',
  'tire',
  'toad',
  'tomb',
  'trap',
  'tree',
  'tuba',
  'tuna',
  'turd',
  'twig',
  'type',
  'undo',
  'vein',
  'vent',
  'vine',
  'vise',
  'vote',
  'walk',
  'wall',
  'warm',
  'wart',
  'wasp',
  'wave',
  'weak',
  'well',
  'west',
  'wife',
  'wind',
  'wine',
  'wing',
  'wire',
  'wolf',
  'wool',
  'work',
  'worm',
  'Xbox',
  'yawn',
  'yeti',
  'Yoda',
  'yolk',
  'Zeus',
  'zoom',
  'Zuma',
  'reed',
  'abyss',
  'AC/DC',
  'acorn',
  'actor',
  'adult',
  'alarm',
  'alien',
  'alley',
  'angel',
  'angry',
  'anime',
  'anvil',
  'Apple',
  'armor',
  'arrow',
  'attic',
  'bacon',
  'bagel',
  'Bambi',
  'banjo',
  'beach',
  'belly',
  'below',
  'bench',
  'Bible',
  'bingo',
  'birch',
  'black',
  'blaze',
  'blimp',
  'blind',
  'blood',
  'blush',
  'board',
  'boots',
  'brain',
  'brand',
  'bread',
  'brick',
  'bride',
  'broom',
  'brush',
  'bulge',
  'bunny',
  'cabin',
  'camel',
  'cello',
  'chain',
  'chair',
  'chalk',
  'cheek',
  'chess',
  'chest',
  'child',
  'chime',
  'China',
  'clean',
  'cliff',
  'climb',
  'cloak',
  'clock',
  'cloth',
  'cloud',
  'clown',
  'coach',
  'coast',
  'cobra',
  'comet',
  'coral',
  'crack',
  'crate',
  'cream',
  'crust',
  'Cupid',
  'curry',
  'daisy',
  'dance',
  'darts',
  'demon',
  'dirty',
  'dizzy',
  'dough',
  'drain',
  'drama',
  'dream',
  'dress',
  'drink',
  'drive',
  'drool',
  'Dumbo',
  'dwarf',
  'eagle',
  'Earth',
  'Egypt',
  'elbow',
  'elder',
  'emoji',
  'error',
  'fairy',
  'Fanta',
  'fence',
  'field',
  'Flash',
  'flask',
  'flock',
  'fluid',
  'flush',
  'flute',
  'frame',
  'fries',
  'frown',
  'fruit',
  'funny',
  'genie',
  'ghost',
  'giant',
  'glass',
  'globe',
  'gloss',
  'glove',
  'gnome',
  'Goofy',
  'goose',
  'graph',
  'grass',
  'grave',
  'greed',
  'grill',
  'groom',
  'gummy',
  'hairy',
  'happy',
  'heart',
  'heist',
  'hijab',
  'hippo',
  'honey',
  'horse',
  'hotel',
  'house',
  'hyena',
  'India',
  'Intel',
  'Italy',
  'Japan',
  'jeans',
  'jello',
  'jelly',
  'Jenga',
  'joker',
  'judge',
  'juice',
  'kazoo',
  'kebab',
  'Kirby',
  'kneel',
  'knife',
  'koala',
  'label',
  'laser',
  'lasso',
  'leash',
  'leave',
  'leech',
  'lemon',
  'lemur',
  'limbo',
  'llama',
  'loser',
  'Luigi',
  'macho',
  'mafia',
  'magic',
  'magma',
  'Mario',
  'match',
  'mayor',
  'melon',
  'messy',
  'metal',
  'miner',
  'model',
  'money',
  'moose',
  'Morty',
  'mouse',
  'mouth',
  'movie',
  'Mummy',
  'night',
  'ninja',
  'north',
  'Notch',
  'novel',
  'nurse',
  'ocean',
  'onion',
  'opera',
  'orbit',
  'organ',
  'otter',
  'paint',
  'panda',
  'pants',
  'paper',
  'Paris',
  'party',
  'pasta',
  'patio',
  'pause',
  'peace',
  'peach',
  'pedal',
  'penny',
  'Pepsi',
  'petal',
  'piano',
  'pilot',
  'pinky',
  'pizza',
  'plank',
  'plate',
  'Pluto',
  'point',
  'poppy',
  'porch',
  'pound',
  'prawn',
  'prism',
  'prune',
  'Pumba',
  'purse',
  'queen',
  'queue',
  'quill',
  'quilt',
  'radar',
  'radio',
  'razor',
  'reeds',
  'river',
  'robin',
  'robot',
  'royal',
  'ruler',
  'salad',
  'Santa',
  'sauce',
  'sauna',
  'scarf',
  'scary',
  'scent',
  'scoop',
  'score',
  'screw',
  'scuba',
  'shake',
  'shape',
  'shark',
  'sheep',
  'shelf',
  'shell',
  'shirt',
  'shock',
  'short',
  'shout',
  'Shrek',
  'shrew',
  'shrub',
  'skull',
  'skunk',
  'Skype',
  'sleep',
  'slide',
  'slime',
  'slope',
  'sloth',
  'slump',
  'smell',
  'smile',
  'smoke',
  'snail',
  'snake',
  'socks',
  'Sonic',
  'sound',
  'south',
  'space',
  'spade',
  'Spain',
  'spark',
  'spear',
  'spine',
  'spool',
  'spoon',
  'spore',
  'squid',
  'stage',
  'stamp',
  'stand',
  'Steam',
  'sting',
  'stone',
  'stork',
  'storm',
  'stove',
  'straw',
  'study',
  'sugar',
  'sushi',
  'swamp',
  'swarm',
  'sweat',
  'swing',
  'sword',
  'table',
  'Tails',
  'taser',
  'thief',
  'think',
  'thumb',
  'tiger',
  'tired',
  'toast',
  'tooth',
  'torch',
  'totem',
  'touch',
  'towel',
  'tower',
  'train',
  'trend',
  'T-rex',
  'truck',
  'tumor',
  'udder',
  'uncle',
  'vault',
  'Venus',
  'video',
  'viola',
  'virus',
  'vodka',
  'vomit',
  'waist',
  'watch',
  'water',
  'whale',
  'wheel',
  'whisk',
  'white',
  'witch',
  'W-LAN',
  'world',
  'wound',
  'wrist',
  'Xerox',
  'x-ray',
  'yacht',
  'Yoshi',
  'young',
  'yo-yo',
  'zebra',
  'Zelda',
  'Zorro',
  'action',
  'Adidas',
  'Africa',
  'airbag',
  'almond',
  'alpaca',
  'anchor',
  'Anubis',
  'archer',
  'armpit',
  'baboon',
  'badger',
  'bakery',
  'ballet',
  'bamboo',
  'banana',
  'banker',
  'barber',
  'barrel',
  'basket',
  'Batman',
  'battle',
  'beanie',
  'beaver',
  'beetle',
  'bellow',
  'betray',
  'bleach',
  'booger',
  'border',
  'bottle',
  'bounce',
  'braces',
  'branch',
  'Brazil',
  'breath',
  'bridge',
  'bronze',
  'bruise',
  'bubble',
  'bucket',
  'bullet',
  'bumper',
  'butler',
  'butter',
  'button',
  'cactus',
  'camera',
  'Canada',
  'canary',
  'candle',
  'cannon',
  'canyon',
  'carpet',
  'carrot',
  'casino',
  'caviar',
  'cement',
  'cheeks',
  'cheese',
  'cherry',
  'Chrome',
  'church',
  'cicada',
  'cinema',
  'circle',
  'circus',
  'clover',
  'cocoon',
  'coffee',
  'coffin',
  'collar',
  'comedy',
  'cookie',
  'copper',
  'corner',
  'corpse',
  'cotton',
  'cousin',
  'cowboy',
  'coyote',
  'crayon',
  'credit',
  'cringe',
  'cruise',
  'cuckoo',
  'cyborg',
  'cymbal',
  'dagger',
  'Darwin',
  'desert',
  'Dexter',
  'diaper',
  'dinner',
  'doctor',
  'dollar',
  'donkey',
  'double',
  'dragon',
  'drawer',
  'driver',
  'earwax',
  'Easter',
  'embers',
  'Eminem',
  'engine',
  'eraser',
  'eskimo',
  'Europe',
  'fabric',
  'facade',
  'family',
  'farmer',
  'father',
  'faucet',
  'filter',
  'finger',
  'flower',
  'folder',
  'forest',
  'fossil',
  'France',
  'fridge',
  'galaxy',
  'Gandhi',
  'garage',
  'garden',
  'garlic',
  'gender',
  'gentle',
  'geyser',
  'goatee',
  'goblin',
  'Google',
  'grapes',
  'gravel',
  'Greece',
  'Grinch',
  'grumpy',
  'guitar',
  'hacker',
  'hammer',
  'handle',
  'hanger',
  'harbor',
  'Hawaii',
  'hazard',
  'health',
  'helmet',
  'hermit',
  'hippie',
  'hobbit',
  'hockey',
  'hunger',
  'hunter',
  'hurdle',
  'icicle',
  'impact',
  'insect',
  'inside',
  'iPhone',
  'island',
  'Israel',
  'jacket',
  'jaguar',
  'jester',
  'juggle',
  'jungle',
  'karate',
  'katana',
  'Kermit',
  'kettle',
  'kidney',
  'kitten',
  'knight',
  'kraken',
  'ladder',
  'laptop',
  'lawyer',
  'leader',
  'lizard',
  'London',
  'lotion',
  'lounge',
  'lyrics',
  'magnet',
  'makeup',
  'mantis',
  'marble',
  'market',
  'marmot',
  'mascot',
  'Medusa',
  'Mexico',
  'Minion',
  'minute',
  'mirror',
  'mohawk',
  'Monday',
  'monkey',
  'mother',
  'Mozart',
  'muffin',
  'muscle',
  'museum',
  'musket',
  'nachos',
  'napkin',
  'NASCAR',
  'nature',
  'needle',
  'nickel',
  'noodle',
  'Norway',
  'nugget',
  'nutmeg',
  'Obelix',
  'office',
  'omelet',
  'orange',
  'orchid',
  'oxygen',
  'oyster',
  'paddle',
  'palace',
  'papaya',
  'parade',
  'parrot',
  'pastry',
  'Paypal',
  'peanut',
  'pencil',
  'pepper',
  'person',
  'pickle',
  'picnic',
  'pigeon',
  'pigsty',
  'pillar',
  'pillow',
  'pimple',
  'pirate',
  'pistol',
  'plague',
  'planet',
  'player',
  'pocket',
  'poison',
  'poodle',
  'Popeye',
  'portal',
  'poster',
  'potato',
  'potion',
  'powder',
  'preach',
  'priest',
  'prince',
  'prison',
  'puddle',
  'puffin',
  'puppet',
  'purity',
  'puzzle',
  'quokka',
  'radish',
  'raisin',
  'rapper',
  'record',
  'Reddit',
  'remote',
  'repeat',
  'retail',
  'rewind',
  'ribbon',
  'robber',
  'rocket',
  'rubber',
  'Russia',
  'saddle',
  'safari',
  'saliva',
  'salmon',
  'Saturn',
  'school',
  'scream',
  'screen',
  'scythe',
  'search',
  'season',
  'second',
  'seesaw',
  'Segway',
  'sensei',
  'server',
  'shadow',
  'shovel',
  'shower',
  'silver',
  'skates',
  'skinny',
  'sledge',
  'sleeve',
  'Slinky',
  'sneeze',
  'sniper',
  'soccer',
  'socket',
  'sphinx',
  'spider',
  'spiral',
  'sponge',
  'sports',
  'spring',
  'square',
  'statue',
  'stereo',
  'stoned',
  'street',
  'stress',
  'strong',
  'studio',
  'stylus',
  'subway',
  'Sudoku',
  'summer',
  'switch',
  'tablet',
  'tailor',
  'tampon',
  'target',
  'Tarzan',
  'tattoo',
  'teapot',
  'tennis',
  'Tetris',
  'thirst',
  'throat',
  'throne',
  'ticket',
  'tickle',
  'tissue',
  'toilet',
  'tomato',
  'tongue',
  'toucan',
  'tripod',
  'trophy',
  'tunnel',
  'turkey',
  'turnip',
  'turtle',
  'tuxedo',
  'Tweety',
  'Uranus',
  'vacuum',
  'valley',
  'vanish',
  'victim',
  'violin',
  'vision',
  'volume',
  'voodoo',
  'vortex',
  'waffle',
  'waiter',
  'Wall-e',
  'walnut',
  'walrus',
  'wealth',
  'weapon',
  'weasel',
  'welder',
  'wiggle',
  'willow',
  'window',
  'winner',
  'winter',
  'wizard',
  'wreath',
  'wrench',
  'writer',
  'yellow',
  'yogurt',
  'zigzag',
  'zipper',
  'zombie',
  'Addida',
  'airport',
  'Aladdin',
  'alcohol',
  'allergy',
  'America',
  'Android',
  'antenna',
  'anthill',
  'apricot',
  'assault',
  'Asterix',
  'athlete',
  'avocado',
  'baklava',
  'balance',
  'balcony',
  'balloon',
  'bandage',
  'bandana',
  'barcode',
  'bathtub',
  'battery',
  'bayonet',
  'bazooka',
  'beatbox',
  'bed bug',
  'bedtime',
  'bicycle',
  'Big Ben',
  'biology',
  'biscuit',
  'Bitcoin',
  'blanket',
  'blender',
  'bobsled',
  'bouncer',
  'bowling',
  'brownie',
  'burglar',
  'burrito',
  'butcher',
  'cabinet',
  'camping',
  'captain',
  'cartoon',
  'catalog',
  'catfish',
  'caveman',
  'ceiling',
  'centaur',
  'charger',
  'cheetah',
  'chicken',
  'chimney',
  'coaster',
  'coconut',
  'compass',
  'concert',
  'console',
  'country',
  'cowbell',
  'Creeper',
  'cricket',
  'Croatia',
  'crowbar',
  'crystal',
  'cupcake',
  'curtain',
  'cushion',
  'defense',
  'dentist',
  'dessert',
  'diagram',
  'diamond',
  'diploma',
  'Discord',
  'disease',
  'dishrag',
  'display',
  'divorce',
  'dolphin',
  'Doritos',
  'Dracula',
  'droplet',
  'drought',
  'earbuds',
  'eclipse',
  'emerald',
  'England',
  'equator',
  'evening',
  'eyebrow',
  'eyelash',
  'factory',
  'failure',
  'feather',
  'fencing',
  'Ferrari',
  'firefly',
  'fireman',
  'Florida',
  'florist',
  'fortune',
  'freezer',
  'funeral',
  'Gandalf',
  'garbage',
  'Germany',
  'giraffe',
  'glasses',
  'glitter',
  'gorilla',
  'gravity',
  'grenade',
  'Gumball',
  'haircut',
  'hammock',
  'hamster',
  'harpoon',
  'hashtag',
  'heading',
  'hexagon',
  'highway',
  'hip hop',
  'holiday',
  'horizon',
  'hot dog',
  'husband',
  'iceberg',
  'Ireland',
  'janitor',
  'jet ski',
  'journey',
  'karaoke',
  'kendama',
  'ketchup',
  'kitchen',
  'knuckle',
  'Kung Fu',
  'ladybug',
  'lantern',
  'Lasagna',
  'laundry',
  'leather',
  'lettuce',
  'library',
  'lighter',
  'lilypad',
  'loading',
  'lobster',
  'lottery',
  'luggage',
  'machine',
  'mailbox',
  'mailman',
  'mammoth',
  'manatee',
  'manhole',
  'mansion',
  'maracas',
  'massage',
  'meerkat',
  'Mercury',
  'mermaid',
  'message',
  'milkman',
  'minivan',
  'missile',
  'monster',
  'morning',
  'Mr Bean',
  'mustard',
  'narwhal',
  'Neptune',
  'network',
  'notepad',
  'nothing',
  'Nutella',
  'octagon',
  'octopus',
  'origami',
  'ostrich',
  'outside',
  'Pac-Man',
  'pajamas',
  'palette',
  'pancake',
  'panther',
  'parents',
  'parking',
  'patient',
  'Patrick',
  'patriot',
  'peacock',
  'peasant',
  'pelican',
  'penguin',
  'perfume',
  'Picasso',
  'pickaxe',
  'Pikachu',
  'pinball',
  'plumber',
  'plunger',
  'Pokemon',
  'popcorn',
  'popular',
  'present',
  'pretzel',
  'printer',
  'protest',
  'provoke',
  'pudding',
  'pumpkin',
  'pyramid',
  'quarter',
  'raccoon',
  'racecar',
  'rainbow',
  'ravioli',
  'reality',
  'referee',
  'reptile',
  'Romania',
  'rooster',
  'Samsung',
  'sandbox',
  'sausage',
  'science',
  'seafood',
  'seagull',
  'seasick',
  'seaweed',
  'shallow',
  'shampoo',
  'shoebox',
  'shotgun',
  'silence',
  'skyline',
  'snowman',
  'soldier',
  'spatula',
  'speaker',
  'spinach',
  'spoiler',
  'stadium',
  'stapler',
  'stomach',
  'student',
  'sunburn',
  'sunrise',
  'surface',
  'surgeon',
  'sweater',
  'tadpole',
  'teacher',
  'thunder',
  'timpani',
  'Titanic',
  'toaster',
  'toenail',
  'toolbox',
  'top hat',
  'tornado',
  'torpedo',
  'tourist',
  'tractor',
  'traffic',
  'trailer',
  'trigger',
  'trumpet',
  'Twitter',
  'Ukraine',
  'ukulele',
  'unibrow',
  'unicorn',
  'uniform',
  'upgrade',
  'vaccine',
  'vampire',
  'vanilla',
  'Vatican',
  'victory',
  'village',
  'villain',
  'vinegar',
  'vitamin',
  'vlogger',
  'volcano',
  'vulture',
  'wake up',
  'weather',
  'website',
  'wedding',
  'western',
  'whisper',
  'whistle',
  'wingnut',
  'witness',
  'wrinkle',
  'Youtube',
  'zipline',
  'abstract',
  'accident',
  'addition',
  'adorable',
  'aircraft',
  'airplane',
  'anaconda',
  'anteater',
  'antelope',
  'applause',
  'aquarium',
  'assassin',
  'asteroid',
  'Atlantis',
  'audience',
  'backbone',
  'backflip',
  'backpack',
  'bagpipes',
  'baguette',
  'Band-Aid',
  'barbecue',
  'basement',
  'bathroom',
  'bean bag',
  'birthday',
  'blizzard',
  'blowfish',
  'bookmark',
  'bracelet',
  'broccoli',
  'brunette',
  'building',
  'bunk bed',
  'bus stop',
  'calendar',
  'campfire',
  'canister',
  'car wash',
  'carnival',
  'catapult',
  'cauldron',
  'Cerberus',
  'chainsaw',
  'champion',
  'chemical',
  'chestnut',
  'clarinet',
  'cocktail',
  'collapse',
  'comedian',
  'complete',
  'computer',
  'confused',
  'corn dog',
  'crossbow',
  'crucible',
  'cucumber',
  'cupboard',
  'customer',
  'cylinder',
  'dandruff',
  'daughter',
  'Deadpool',
  'delivery',
  'detonate',
  'diagonal',
  'dinosaur',
  'disaster',
  'distance',
  'doghouse',
  'dominoes',
  'doorknob',
  'download',
  'drum kit',
  'dynamite',
  'eggplant',
  'Einstein',
  'election',
  'elephant',
  'elevator',
  'employer',
  'engineer',
  'espresso',
  'exercise',
  'fabulous',
  'Facebook',
  'festival',
  'figurine',
  'fireball',
  'fireside',
  'firework',
  'flagpole',
  'flamingo',
  'forehead',
  'fortress',
  'fountain',
  'freckles',
  'frosting',
  'gangster',
  'gardener',
  'Garfield',
  'gas mask',
  'gasoline',
  'goldfish',
  'graffiti',
  'handicap',
  'hard hat',
  'hay bale',
  'hazelnut',
  'headache',
  'headband',
  'hedgehog',
  'Hercules',
  'homeless',
  'hospital',
  'industry',
  'infinite',
  'insomnia',
  'internet',
  'invasion',
  'Iron Man',
  'jalapeno',
  'kangaroo',
  'keyboard',
  'landlord',
  'language',
  'lemonade',
  'levitate',
  'licorice',
  'lipstick',
  'lollipop',
  'macaroni',
  'magazine',
  'magician',
  'manicure',
  'marathon',
  'marigold',
  'matchbox',
  'mattress',
  'meatball',
  'meatloaf',
  'mechanic',
  'Mercedes',
  'midnight',
  'military',
  'Miniclip',
  'minigolf',
  'minority',
  'Minotaur',
  'mosquito',
  'mothball',
  'mountain',
  'Mr. Bean',
  'murderer',
  'mushroom',
  'mustache',
  'neighbor',
  'nostrils',
  'notebook',
  'nutshell',
  'panpipes',
  'parakeet',
  'password',
  'pavement',
  'pendulum',
  'pet food',
  'pet shop',
  'pinwheel',
  'platypus',
  'ponytail',
  'Popsicle',
  'portrait',
  'Portugal',
  'Poseidon',
  'positive',
  'postcard',
  'pregnant',
  'princess',
  'Pringles',
  'raincoat',
  'raindrop',
  'reindeer',
  'religion',
  'revolver',
  'ringtone',
  'rockstar',
  'sailboat',
  'sandwich',
  'scissors',
  'Scotland',
  'scribble',
  'sea lion',
  'seahorse',
  'seashell',
  'security',
  'shoelace',
  'shopping',
  'shoulder',
  'six pack',
  'skeleton',
  'ski jump',
  'Skittles',
  'Skrillex',
  'slippery',
  'snowball',
  'sombrero',
  'sparkles',
  'squirrel',
  'starfish',
  'stingray',
  'streamer',
  'suitcase',
  'sunshade',
  'Superman',
  'survivor',
  'swimsuit',
  'symphony',
  'tabletop',
  'take off',
  'teaspoon',
  'tentacle',
  'tiramisu',
  'tortoise',
  'trapdoor',
  'traveler',
  'treasure',
  'triangle',
  'tricycle',
  'triplets',
  'trombone',
  'tropical',
  'umbrella',
  'unicycle',
  'universe',
  'vacation',
  'vertical',
  'violence',
  'vuvuzela',
  'werewolf',
  'WhatsApp',
  'windmill',
  'wireless',
  'wrapping',
  'wrestler',
  'yearbook',
  'youtuber',
  'zeppelin',
  'accordion',
  'addiction',
  'afterlife',
  'albatross',
  'alligator',
  'ambulance',
  'Amsterdam',
  'animation',
  'antivirus',
  'apartment',
  'apple pie',
  'architect',
  'Argentina',
  'armadillo',
  'astronaut',
  'asymmetry',
  'Australia',
  'autograph',
  'back pain',
  'ballerina',
  'barbarian',
  'bartender',
  'beanstalk',
  'bear trap',
  'bed sheet',
  'Beethoven',
  'billiards',
  'bird bath',
  'blindfold',
  'blueberry',
  'bodyguard',
  'Bomberman',
  'bookshelf',
  'boomerang',
  'brainwash',
  'breakfast',
  'broadcast',
  'Bruce Lee',
  'bulldozer',
  'butterfly',
  'Capricorn',
  'cardboard',
  'carnivore',
  'carpenter',
  'Cat Woman',
  'cathedral',
  'celebrate',
  'celebrity',
  'centipede',
  'chameleon',
  'champagne',
  'Chewbacca',
  'chihuahua',
  'Chinatown',
  'chocolate',
  'Christmas',
  'cigarette',
  'classroom',
  'clickbait',
  'clownfish',
  'cockroach',
  'Colosseum',
  'commander',
  'communism',
  'community',
  'condiment',
  'continent',
  'corkscrew',
  'cornfield',
  'crocodile',
  'croissant',
  'dalmatian',
  'dandelion',
  'dashboard',
  'deodorant',
  'depressed',
  'desperate',
  'detective',
  'dispenser',
  'dollhouse',
  'dragonfly',
  'duct tape',
  'Elon Musk',
  'evaporate',
  'evolution',
  'Excalibur',
  'excavator',
  'explosion',
  'eyeshadow',
  'fast food',
  'filmmaker',
  'fingertip',
  'firehouse',
  'fireplace',
  'fireproof',
  'fish bowl',
  'fisherman',
  'frostbite',
  'full moon',
  'furniture',
  'generator',
  'gentleman',
  'geography',
  'gladiator',
  'glowstick',
  'godfather',
  'golf cart',
  'graveyard',
  'hairbrush',
  'hairspray',
  'hamburger',
  'handshake',
  'harmonica',
  'headboard',
  'hibernate',
  'high five',
  'hilarious',
  'Hollywood',
  'honeycomb',
  'hopscotch',
  'horsewhip',
  'hot sauce',
  'hourglass',
  'Hula Hoop',
  'hypnotize',
  'ice cream',
  'incognito',
  'injection',
  'interview',
  'invention',
  'invisible',
  'jellyfish',
  'John Cena',
  'jump rope',
  'junk food',
  'King Kong',
  'Lady Gaga',
  'landscape',
  'Las Vegas',
  'lava lamp',
  'librarian',
  'lightbulb',
  'lightning',
  'limousine',
  'Lion King',
  'magnifier',
  'mannequin',
  'margarine',
  'marmalade',
  'McDonalds',
  'megaphone',
  'meteorite',
  'Microsoft',
  'microwave',
  'milkshake',
  'Milky Way',
  'Minecraft',
  'Mona Lisa',
  'motorbike',
  'mousetrap',
  'nail file',
  'newspaper',
  'nightclub',
  'nightmare',
  'nose hair',
  'nose ring',
  'nosebleed',
  'orangutan',
  'orchestra',
  'paintball',
  'palm tree',
  'paper bag',
  'parachute',
  'peninsula',
  'pensioner',
  'Peppa Pig',
  'pepperoni',
  'periscope',
  'Photoshop',
  'pine cone',
  'pineapple',
  'Pinocchio',
  'pistachio',
  'pitchfork',
  'poisonous',
  'policeman',
  'pollution',
  'porcupine',
  'Porky Pig',
  'president',
  'price tag',
  'professor',
  'promotion',
  'quicksand',
  'radiation',
  'raspberry',
  'reception',
  'rectangle',
  'recycling',
  'roadblock',
  'saltwater',
  'sandstorm',
  'satellite',
  'saxophone',
  'scarecrow',
  'scientist',
  'sculpture',
  'seat belt',
  'shipwreck',
  'signature',
  'Singapore',
  'skydiving',
  'slingshot',
  'snowboard',
  'snowflake',
  'spaceship',
  'spaghetti',
  'Spartacus',
  'spelunker',
  'Spiderman',
  'SpongeBob',
  'sprinkler',
  'Squidward',
  'Star Wars',
  'starfruit',
  'Stone Age',
  'stop sign',
  'submarine',
  'sunflower',
  'surfboard',
  'swordfish',
  'tangerine',
  'tarantula',
  'telephone',
  'telescope',
  'Teletubby',
  'tombstone',
  'toothpick',
  'tow truck',
  'translate',
  'trash can',
  'treadmill',
  'treehouse',
  'Vault boy',
  'vegetable',
  'wallpaper',
  'warehouse',
  'water gun',
  'waterfall',
  'Wolverine',
  'workplace',
  'wrestling',
  'xylophone',
  'yardstick',
  'shoulders',
  'anglerfish',
  'Antarctica',
  'apocalypse',
  'apple seed',
  'aristocrat',
  'basketball',
  'battleship',
  'Bill Gates',
  'binoculars',
  'black hole',
  'blackberry',
  'blacksmith',
  'bricklayer',
  'broomstick',
  'bubble gum',
  'Bugs Bunny',
  'bus driver',
  'cab driver',
  'can opener',
  'cappuccino',
  'cell phone',
  'chandelier',
  'cheesecake',
  'chest hair',
  'chestplate',
  'chimpanzee',
  'chinchilla',
  'chopsticks',
  'comic book',
  'commercial',
  'controller',
  'cookie jar',
  'coral reef',
  'Daffy Duck',
  'dictionary',
  'diss track',
  'earthquake',
  'face paint',
  'fake teeth',
  'Family Guy',
  'fingernail',
  'fire alarm',
  'fire truck',
  'fist fight',
  'flashlight',
  'floodlight',
  'flying pig',
  'glue stick',
  'gold chain',
  'golden egg',
  'graduation',
  'grapefruit',
  'Great Wall',
  'guillotine',
  'guinea pig',
  'gummy bear',
  'gummy worm',
  'Happy Meal',
  'headphones',
  'helicopter',
  'hieroglyph',
  'high heels',
  'high score',
  'hitchhiker',
  'Home Alone',
  'hovercraft',
  'Iron Giant',
  'jackhammer',
  'James Bond',
  'journalist',
  'Katy Perry',
  'laboratory',
  'lawn mower',
  'leprechaun',
  'lighthouse',
  'lightsaber',
  'litter box',
  'London Eye',
  'lumberjack',
  'Madagascar',
  'magic wand',
  'mayonnaise',
  'microphone',
  'microscope',
  'Mont Blanc',
  'Morse code',
  'motorcycle',
  'nutcracker',
  'overweight',
  'pharmacist',
  'photograph',
  'piggy bank',
  'playground',
  'pogo stick',
  'polar bear',
  'programmer',
  'punishment',
  'rainforest',
  'razorblade',
  'red carpet',
  'reflection',
  'restaurant',
  'rhinoceros',
  'Robin Hood',
  'Scooby Doo',
  'semicircle',
  'silverware',
  'skateboard',
  'skribbl.io',
  'skyscraper',
  'space suit',
  'Steve Jobs',
  'strawberry',
  'Suez Canal',
  'sunglasses',
  'superpower',
  'tablecloth',
  'teddy bear',
  'television',
  'Terminator',
  'tissue box',
  'toothbrush',
  'toothpaste',
  'trick shot',
  'Usain Bolt',
  'vegetarian',
  'video game',
  'Vin Diesel',
  'volleyball',
  'windshield',
  'wine glass',
  'wonderland',
  'woodpecker',
  'Angry Birds',
  'barbed wire',
  'bell pepper',
  'bottle flip',
  'butt cheeks',
  'caterpillar',
  'cauliflower',
  'ceiling fan',
  'cheerleader',
  'coast guard',
  'coffee shop',
  'color-blind',
  'comfortable',
  'crawl space',
  'credit card',
  'Donald Duck',
  'electrician',
  'electricity',
  'firecracker',
  'firefighter',
  'fishing rod',
  'floppy disk',
  'fly swatter',
  'forest fire',
  'grandmother',
  'grasshopper',
  'gravedigger',
  'hair roller',
  'Hello Kitty',
  'hummingbird',
  'imagination',
  'Jackie Chan',
  'Kim Jong-un',
  'magic trick',
  'marshmallow',
  'motherboard',
  'Mr Meeseeks',
  'nail polish',
  'Netherlands',
  'New Zealand',
  'North Korea',
  'observatory',
  'pencil case',
  'photo frame',
  'pirate ship',
  'Playstation',
  'sand castle',
  'spray paint',
  'Stegosaurus',
  'supermarket',
  'talent show',
  'taxi driver',
  'temperature',
  'The Beatles',
  'thermometer',
  'Tooth Fairy',
  'tuning fork',
  'underground',
  'underweight',
  'water cycle',
  'wheelbarrow',
  'Barack Obama',
  'Bart Simpson',
  'belly button',
  'Black Friday',
  'bowling alley',
  'broken heart',
  'cheeseburger',
  'Chuck Norris',
  'conversation',
  'cotton candy',
  'Donald Trump',
  'Easter Bunny',
  'Eiffel tower',
  'electric car',
  'fast forward',
  'fire hydrant',
  'flamethrower',
  'Frankenstein',
  'golden apple',
  'Harry Potter',
  'intersection',
  'Jesus Christ',
  'Johnny Bravo',
  'kindergarten',
  'Mickey Mouse',
  'Mr. Meeseeks',
  'neighborhood',
  'notification',
  'photographer',
  'pillow fight',
  'Pink Panther',
  'receptionist',
  'relationship',
  'skateboarder',
  'sledgehammer',
  'social media',
  'Solar System',
  'table tennis',
  'thunderstorm',
  'time machine',
  'Tower Bridge',
  'truck driver',
  'Velociraptor',
  'veterinarian',
  'Wonder Woman',
  'advertisement',
  'archaeologist',
  'demonstration',
  'Green Lantern',
  'Homer Simpson',
  'hot chocolate',
  'Jimmy Neutron',
  'Mount Everest',
  'Robbie Rotten',
  'shaving cream',
  'shopping cart',
  'snake charmer',
  'swimming pool',
  'tennis racket',
  'traffic light',
  'Angelina Jolie',
  'bungee jumping',
  'cherry blossom',
  'clothes hanger',
  'Cookie Monster',
  'fidget spinner',
  'Jack-o-lantern',
  'Morgan Freeman',
  'Mount Rushmore',
  'reading glasses',
  'sewing machine',
  'snowball fight',
  'Susan Wojcicki',
  'Abraham Lincoln',
  'air conditioner',
  'Captain America',
  'Charlie Chaplin',
  'Crash Bandicoot',
  'electric guitar',
  'fitness trainer',
  'Fred Flintstone',
  'Mark Zuckerberg',
  'Michael Jackson',
  'Nintendo Switch',
  'Northern Lights',
  'procrastination',
  'Sherlock Holmes',
  'virtual reality',
  'William Wallace',
  'Darwin Watterson',
  'fashion designer',
  'flight attendant',
  'pencil sharpener',
  'Leonardo DiCaprio',
  'William Shakespeare',
  'yo yo',
  'bobcat',
  'iguana',
  'jackal',
  'bow tie',
  'cyclone',
  'doormat',
  'fox den',
  'glacier',
  'gondola',
  'hot tub',
  'jam jar',
  'mat rug',
  'monsoon',
  'mudflat',
  'musk ox',
  'oil rig',
  'opossum',
  'pig pen',
  'piranha',
  'rag rug',
  'rowboat',
  'sun hat',
  'tie dye',
  'tin can',
  'tugboat',
  'warthog',
  'ant hill',
  'barn owl',
  'bath mat',
  'bee hive',
  'biathlon',
  'capybara',
  'cat tree',
  'cockatoo',
  'cow barn',
  'dog sled',
  'drum set',
  'dumpling',
  'dust pan',
  'ear ring',
  'eye exam',
  'fire ant',
  'fire pit',
  'flu shot',
  'forklift',
  'fur coat',
  'gargoyle',
  'gemstone',
  'gift box',
  'hand bag',
  'hat rack',
  'hay ride',
  'herb pot',
  'ice cube',
  'ice tray',
  'key ring',
  'kid pool',
  'knee pad',
  'lab coat',
  'ladybird',
  'log ride',
  'lynx paw',
  'mandrill',
  'mongoose',
  'monorail',
  'mudslide',
  'mug rack',
  'mug shot',
  'nail gun',
  'nap time',
  'necklace',
  'nerf gun',
  'nest egg',
  'oak tree',
  'overalls',
  'pheasant',
  'pool cue',
  'porpoise',
  'race car',
  'rat trap',
  'rickshaw',
  'row boat',
  'ruby gem',
  'sculptor',
  'sea cave',
  'shot put',
  'sled dog',
  'snowplow',
  'stew pot',
  'sun dial',
  'tag team',
  'tank top',
  'taxi cab',
  'toe nail',
  'toolbelt',
  'tow rope',
  'wet suit',
  'wig shop',
  'wishbone',
  'worm bin',
  'yoga mat',
  'zip line',
  'zoo cage',
  'zucchini',
  'angelfish',
  'artichoke',
  'asparagus',
  'bear cave',
  'bed frame',
  'beekeeper',
  'bike rack',
  'bird cage',
  'book fair',
  'bratwurst',
  'bumblebee',
  'cable car',
  'camp fire',
  'chain saw',
  'city hall',
  'city park',
  'coal mine',
  'cormorant',
  'crab claw',
  'crossword',
  'daredevil',
  'dartboard',
  'desk lamp',
  'dice game',
  'dice roll',
  'dirt bike',
  'dish rack',
  'dodo bird',
  'dog house',
  'dog leash',
  'door bell',
  'door knob',
  'drive way',
  'dromedary',
  'drum solo',
  'duck pond',
  'elbow pad',
  'enchilada',
  'end table',
  'exit sign',
  'eye patch',
  'farmhouse',
  'fish pond',
  'fish tank',
  'flag pole',
  'flashcard',
  'flat tire',
  'flowerpot',
  'fork lift',
  'geologist',
  'glass jar',
  'glove box',
  'gold coin',
  'gold mine',
  'goldfinch',
  'golf ball',
  'guard dog',
  'gym class',
  'hairdryer',
  'half pipe',
  'hand soap',
  'handcuffs',
  'hat trick',
  'head band',
  'heat wave',
  'high dive',
  'horseshoe',
  'hound dog',
  'house key',
  'houseboat',
  'hurricane',
  'hydrofoil',
  'ice sheet',
  'incubator',
  'iron gate',
  'jazz band',
  'juice box',
  'junk yard',
  'key chain',
  'kiwi bird',
  'lamp post',
  'lampshade',
  'land mine',
  'lava flow',
  'lava rock',
  'lifeguard',
  'locksmith',
  'log cabin',
  'log flume',
  'long jump',
  'lost city',
  'lunch box',
  'mail slot',
  'mistletoe',
  'money jar',
  'moth ball',
  'moth wing',
  'motorboat',
  'mule cart',
  'navy ship',
  'newt pond',
  'nightgown',
  'nine ball',
  'nut shell',
  'oven rack',
  'panda cub',
  'paperclip',
  'party hat',
  'peg board',
  'pet leash',
  'piano key',
  'ping pong',
  'plant pot',
  'plush toy',
  'polar cap',
  'pony ride',
  'pork chop',
  'propeller',
  'queen bee',
  'quiz show',
  'race flag',
  'raft trip',
  'rain coat',
  'red panda',
  'reef fish',
  'rest stop',
  'ring toss',
  'riverbank',
  'robot arm',
  'rock band',
  'sail boat',
  'salt mine',
  'sand dune',
  'sandpiper',
  'sauce pan',
  'sea otter',
  'sea shell',
  'shark fin',
  'shoe lace',
  'shoe rack',
  'shoreline',
  'ski lodge',
  'ski slope',
  'sky diver',
  'snow fort',
  'snow plow',
  'soap dish',
  'song bird',
  'soup bowl',
  'spice jar',
  'stopwatch',
  'stove top',
  'straw hat',
  'swan boat',
  'swim lane',
  'swing set',
  'table saw',
  'tap dance',
  'tea party',
  'tent pole',
  'test tube',
  'tide pool',
  'tire iron',
  'tire shop',
  'tool belt',
  'toy chest',
  'trail map',
  'trash bin',
  'triathlon',
  'truck bed',
  'turntable',
  'twig nest',
  'violinist',
  'wine cork',
  'wine rack',
  'wing span',
  'wolf howl',
  'woodchuck',
  'yard sale',
  'yarn ball',
  'zoologist',
  'alarm bell',
  'alien ship',
  'ankle sock',
  'astronomer',
  'backpacker',
  'bat colony',
  'bath towel',
  'beach ball',
  'beach sand',
  'beef jerky',
  'blimp ride',
  'bloodhound',
  'board game',
  'bocce ball',
  'bomb squad',
  'book stand',
  'bottle cap',
  'brass band',
  'bread loaf',
  'brick oven',
  'brick wall',
  'camel hump',
  'campground',
  'candy cane',
  'candy shop',
  'cannonball',
  'canoe trip',
  'cargo ship',
  'cartoonist',
  'cereal box',
  'chalk line',
  'class room',
  'coffee mug',
  'coin purse',
  'comet tail',
  'cork board',
  'crayon box',
  'cuttlefish',
  'desk chair',
  'dingo pack',
  'dishwasher',
  'doll house',
  'donut hole',
  'donut shop',
  'door hinge',
  'drug store',
  'dump truck',
  'dust bunny',
  'dust storm',
  'dvd player',
  'eagle nest',
  'fairground',
  'fence post',
  'fennec fox',
  'field goal',
  'field trip',
  'fire chief',
  'fire drill',
  'flip flops',
  'floor lamp',
  'floor tile',
  'flute note',
  'food truck',
  'fork spoon',
  'fruit bowl',
  'frying pan',
  'gate latch',
  'genie lamp',
  'ginger cat',
  'grain silo',
  'grape vine',
  'gymnastics',
  'hail storm',
  'hammerhead',
  'hamper lid',
  'hand cream',
  'hash brown',
  'helmet cam',
  'hill slope',
  'hive honey',
  'hobby shop',
  'honey bear',
  'hoof print',
  'horse race',
  'hula dance',
  'hummus dip',
  'ice hockey',
  'ice palace',
  'icebreaker',
  'interstate',
  'ivory tusk',
  'judo throw',
  'juggernaut',
  'kayak trip',
  'kennel dog',
  'king cobra',
  'kiwi fruit',
  'knot tying',
  'koala bear',
  'lake house',
  'lake shore',
  'lasso rope',
  'law office',
  'lawn chair',
  'lemur tail',
  'letter box',
  'life coach',
  'light bulb',
  'lion tamer',
  'litter bin',
  'llama farm',
  'llama wool',
  'locomotive',
  'lost puppy',
  'lunch tray',
  'magic show',
  'maple leaf',
  'marble bag',
  'milk shake',
  'money tree',
  'mop bucket',
  'motel sign',
  'mouse trap',
  'moving van',
  'mudskipper',
  'muffin pan',
  'muffin top',
  'mule trail',
  'mummy wrap',
  'muscle car',
  'nail salon',
  'oasis palm',
  'oil tanker',
  'onion ring',
  'orca whale',
  'otter pond',
  'paintbrush',
  'paraglider',
  'park bench',
  'peach tree',
  'perch fish',
  'percussion',
  'permafrost',
  'pickpocket',
  'pilgrimage',
  'pirate hat',
  'pizza oven',
  'pole vault',
  'pool table',
  'quail nest',
  'quarry pit',
  'quesadilla',
  'race track',
  'radar dish',
  'rail track',
  'rain boots',
  'rhino horn',
  'rice paddy',
  'ridge line',
  'ringmaster',
  'river bank',
  'river raft',
  'roadrunner',
  'rodeo bull',
  'salad bowl',
  'salamander',
  'sand storm',
  'sandcastle',
  'school bus',
  'scrap yard',
  'scuba dive',
  'scuba gear',
  'scuba tank',
  'semi truck',
  'sewer pipe',
  'shark tank',
  'sheep herd',
  'skate park',
  'skate ramp',
  'snail race',
  'snorkeling',
  'snow globe',
  'snow storm',
  'soap opera',
  'sound wave',
  'sour cream',
  'speed boat',
  'speed bump',
  'spice rack',
  'spider web',
  'sports car',
  'spy gadget',
  'stagecoach',
  'stalactite',
  'stalagmite',
  'state fair',
  'steel beam',
  'step stool',
  'stone arch',
  'stove knob',
  'sugar cube',
  'sunset sky',
  'surf board',
  'sushi roll',
  'suspenders',
  'swamp boat',
  'table lamp',
  'taco truck',
  'tarp cover',
  'taxi meter',
  'tent stake',
  'theme park',
  'thermostat',
  'thumb tack',
  'tidal wave',
  'tiger cage',
  'tile floor',
  'tire swing',
  'toll booth',
  'tour guide',
  'towel rack',
  'trampoline',
  'travel bag',
  'tray table',
  'tree house',
  'tree stump',
  'trial jury',
  'trombonist',
  'truck stop',
  'tulip bulb',
  'tumbleweed',
  'tundra fox',
  'tv antenna',
  'typewriter',
  'upholstery',
  'video call',
  'vine grape',
  'violin bow',
  'viper fang',
  'wall clock',
  'wash basin',
  'wash cloth',
  'watchtower',
  'water park',
  'water polo',
  'water tank',
  'watercolor',
  'waterslide',
  'wax candle',
  'wheelchair',
  'whip cream',
  'wind chime',
  'wizard hat',
  'wood stove',
  'worker bee',
  'wrench set',
  'wristwatch',
  'yacht club',
  'yacht sail',
  'yard stick',
  'zebra herd',
  'alarm clock',
  'art gallery',
  'bakery oven',
  'barber pole',
  'belt buckle',
  'block party',
  'boat anchor',
  'bobsled run',
  'bowling pin',
  'bread knife',
  'bubble bath',
  'bucket list',
  'bumper cars',
  'bungee jump',
  'button hole',
  'cabin fever',
  'camera lens',
  'candlestick',
  'canyon echo',
  'canyon hike',
  'cargo pants',
  'cargo plane',
  'carpet roll',
  'chalk board',
  'cheese cake',
  'cheese shop',
  'chess board',
  'chess piece',
  'circus tent',
  'clarinetist',
  'cliffhanger',
  'clock tower',
  'closet door',
  'cloud shape',
  'cobblestone',
  'comedy club',
  'comic strip',
  'cooking pot',
  'copper pipe',
  'coral snake',
  'cotton swab',
  'coyote howl',
  'cricket bat',
  'crime scene',
  'cruise ship',
  'curtain rod',
  'dance floor',
  'deviled egg',
  'diving pool',
  'dog groomer',
  'donkey cart',
  'dragon fire',
  'drama class',
  'drapery rod',
  'dress shirt',
  'dry cleaner',
  'eagle scout',
  'eagle talon',
  'elk antlers',
  'escape room',
  'exoskeleton',
  'falcon dive',
  'family tree',
  'faucet leak',
  'feather boa',
  'fingerprint',
  'fire engine',
  'fish market',
  'fishing net',
  'fjord coast',
  'flea circus',
  'flea market',
  'flower shop',
  'fog machine',
  'fruit salad',
  'garden hose',
  'garden shed',
  'gas station',
  'gate keeper',
  'ghost story',
  'glassblower',
  'golf course',
  'goose flock',
  'grand piano',
  'grape juice',
  'grass field',
  'gravel road',
  'guitar case',
  'gutter pipe',
  'gym workout',
  'hairdresser',
  'harp string',
  'heated pool',
  'heater vent',
  'herb garden',
  'hermit crab',
  'high school',
  'hiking pole',
  'hockey game',
  'hockey mask',
  'hockey puck',
  'hostel room',
  'hot balloon',
  'hover board',
  'hut village',
  'hydro power',
  'hyena laugh',
  'ice fishing',
  'ice skating',
  'icicle drip',
  'illusionist',
  'illustrator',
  'impala leap',
  'jelly donut',
  'jewelry box',
  'jungle vine',
  'junior high',
  'karate belt',
  'kitchenware',
  'kite string',
  'laundry day',
  'lemon slice',
  'life jacket',
  'lily flower',
  'liquid soap',
  'living room',
  'locker room',
  'love letter',
  'luggage tag',
  'lumber mill',
  'marina dock',
  'maze puzzle',
  'mesh screen',
  'milk bottle',
  'mirror ball',
  'mirror maze',
  'mixing bowl',
  'mobile home',
  'model train',
  'mole tunnel',
  'moon crater',
  'morning dew',
  'mosque dome',
  'museum tour',
  'napkin ring',
  'night light',
  'noodle bowl',
  'noodle shop',
  'nut cracker',
  'ocean liner',
  'office desk',
  'onion patch',
  'opera house',
  'ostrich egg',
  'outer space',
  'owl feather',
  'oxygen mask',
  'paddle boat',
  'paper plane',
  'paper stack',
  'paper towel',
  'parrot cage',
  'pasta maker',
  'pearl diver',
  'pepper mill',
  'philatelist',
  'phone booth',
  'photo album',
  'photo booth',
  'picket line',
  'pigeon coop',
  'pillow case',
  'pillow fort',
  'pine forest',
  'planetarium',
  'pomegranate',
  'pool noodle',
  'popcorn bag',
  'porch light',
  'porch swing',
  'post office',
  'potato sack',
  'power drill',
  'power plant',
  'prison bars',
  'prison cell',
  'pterodactyl',
  'pumpkin pie',
  'puppy leash',
  'python coil',
  'quilt cover',
  'rabbit hole',
  'racquetball',
  'radiologist',
  'rain forest',
  'rain puddle',
  'ranch house',
  'raven perch',
  'rescue boat',
  'rock garden',
  'rodeo clown',
  'roller rink',
  'rolling pin',
  'root cellar',
  'rope bridge',
  'rose garden',
  'rowing boat',
  'rowing crew',
  'rubber boot',
  'rubber duck',
  'rugby scrum',
  'saber tooth',
  'sailor knot',
  'salt shaker',
  'saxophonist',
  'school bell',
  'school desk',
  'school play',
  'science lab',
  'scissor cut',
  'screen door',
  'screwdriver',
  'scuba diver',
  'seagull cry',
  'secret door',
  'seed packet',
  'segway ride',
  'shelf brace',
  'shield wall',
  'shrimp boat',
  'silver mine',
  'skunk spray',
  'smoke alarm',
  'snail shell',
  'soap bubble',
  'soccer ball',
  'sock puppet',
  'solar flare',
  'solar panel',
  'speaker box',
  'spider bite',
  'spider legs',
  'sprint race',
  'steak knife',
  'stethoscope',
  'stool chair',
  'storage bin',
  'storm cloud',
  'storm drain',
  'street lamp',
  'street sign',
  'suit jacket',
  'summer camp',
  'swamp marsh',
  'sword fight',
  'table cloth',
  'tailor shop',
  'tandem bike',
  'tanning bed',
  'taxidermist',
  'temple gate',
  'tennis ball',
  'throne room',
  'tooth brush',
  'tote basket',
  'toucan beak',
  'toy factory',
  'traffic jam',
  'trash truck',
  'trench coat',
  'triceratops',
  'trolley car',
  'tuba player',
  'tulip field',
  'tumbler cup',
  'turtle dove',
  'upholsterer',
  'valley view',
  'vase flower',
  'veggie tray',
  'vintage car',
  'violin case',
  'volcano ash',
  'volcano top',
  'waffle cone',
  'wagon train',
  'wagon wheel',
  'wall poster',
  'wall socket',
  'walrus tusk',
  'watch tower',
  'water tower',
  'weathervane',
  'well bucket',
  'whale shark',
  'wheat field',
  'willow tree',
  'window pane',
  'window sill',
  'wine bottle',
  'wine cellar',
  'winter coat',
  'wire hanger',
  'witch broom',
  'wrist brace',
  'xylophonist',
  'zebra print',
  'zigzag path',
  'zipper pull',
  'zoo exhibit',
  'acrobat flip',
  'anchor chain',
  'apricot tree',
  'archeologist',
  'architecture',
  'attic ladder',
  'baboon troop',
  'baked potato',
  'balance beam',
  'balloon ride',
  'bamboo shoot',
  'banana split',
  'band concert',
  'banjo player',
  'beetle shell',
  'bengal tiger',
  'bicycle bell',
  'blanket fort',
  'bounce house',
  'boxing match',
  'bread basket',
  'broom closet',
  'buffalo herd',
  'burger stand',
  'bus terminal',
  'butcher shop',
  'butter churn',
  'butterscotch',
  'cabinet door',
  'camera flash',
  'canoe rental',
  'canyon cliff',
  'car mechanic',
  'castle tower',
  'cement mixer',
  'cement truck',
  'chicken coop',
  'chicken farm',
  'circus clown',
  'city skyline',
  'clam chowder',
  'cobra strike',
  'coconut milk',
  'coconut tree',
  'coffee table',
  'cold storage',
  'compass rose',
  'construction',
  'cotton field',
  'country road',
  'cowboy boots',
  'crab fishing',
  'credit union',
  'crystal ball',
  'dance studio',
  'desert camel',
  'desert oasis',
  'diamond mine',
  'diamond ring',
  'dinner plate',
  'dinner table',
  'dinosaur egg',
  'diving board',
  'dolphin jump',
  'dolphin show',
  'domino chain',
  'dragon fruit',
  'drone flight',
  'electric eel',
  'electric fan',
  'emerald ring',
  'evening star',
  'exhaust pipe',
  'falafel wrap',
  'farm tractor',
  'ferris wheel',
  'field hockey',
  'fire station',
  'fishing boat',
  'fishing lure',
  'fishing pier',
  'florist shop',
  'forest trail',
  'fountain pen',
  'french toast',
  'funeral home',
  'garden gnome',
  'gazelle herd',
  'gecko lizard',
  'gila monster',
  'giraffe neck',
  'glass window',
  'glider plane',
  'glockenspiel',
  'grand canyon',
  'grill master',
  'grizzly bear',
  'grocery cart',
  'grocery list',
  'hair stylist',
  'hang gliding',
  'hiking boots',
  'hiking trail',
  'hippopotamus',
  'hockey stick',
  'honey badger',
  'horse saddle',
  'horse stable',
  'hospital bed',
  'jaguar spots',
  'kaleidoscope',
  'kayak paddle',
  'kitchen sink',
  'laundry soap',
  'library book',
  'library card',
  'linen closet',
  'loading dock',
  'lobster trap',
  'loom weaving',
  'luggage cart',
  'macaw parrot',
  'machine shop',
  'magic carpet',
  'mail carrier',
  'market stall',
  'meadow field',
  'meatball sub',
  'midnight sky',
  'mirror frame',
  'mixing spoon',
  'mobile phone',
  'moon landing',
  'motor engine',
  'movie camera',
  'movie ticket',
  'music studio',
  'nature trail',
  'night market',
  'night vision',
  'nursing home',
  'oatmeal bowl',
  'office chair',
  'oil painting',
  'olive branch',
  'omelette pan',
  'opera singer',
  'orange grove',
  'orthodontist',
  'oyster shell',
  'paddle wheel',
  'paint bucket',
  'paint roller',
  'pajama party',
  'pancake flip',
  'pantry shelf',
  'papaya slice',
  'parade float',
  'parkour jump',
  'pediatrician',
  'pelican beak',
  'pepper spray',
  'picket fence',
  'picnic table',
  'picture hook',
  'planet earth',
  'pocket watch',
  'pontoon boat',
  'power outage',
  'radish patch',
  'roast turkey',
  'roller blade',
  'roller derby',
  'roof shingle',
  'rose bouquet',
  'royal throne',
  'rustic cabin',
  'sailing race',
  'sandbox play',
  'sausage link',
  'science fair',
  'seismologist',
  'selfie stick',
  'shirt button',
  'shopping bag',
  'sign painter',
  'singing bowl',
  'skunk stripe',
  'sleeping bag',
  'slipper sock',
  'sneaker shoe',
  'snow leopard',
  'soccer match',
  'spatula flip',
  'spelling bee',
  'spinning top',
  'spool thread',
  'sports arena',
  'spray bottle',
  'spring bloom',
  'stadium seat',
  'stage lights',
  'stapler clip',
  'steam engine',
  'steam roller',
  'stick figure',
  'stock market',
  'storage unit',
  'stove burner',
  'stretch limo',
  'stuffed bear',
  'stunt double',
  'summit climb',
  'sun umbrella',
  'surgeon mask',
  'sweater vest',
  'swim goggles',
  'syrup bottle',
  'talent agent',
  'tape measure',
  'tennis court',
  'thread spool',
  'thrift store',
  'throw pillow',
  'thunder clap',
  'ticket booth',
  'toboggan run',
  'toilet brush',
  'toilet paper',
  'tomato sauce',
  'tractor tire',
  'traffic cone',
  'train ticket',
  'trout stream',
  'tugboat dock',
  'tundra plain',
  'turnip patch',
  'turtle shell',
  'unicorn horn',
  'utility pole',
  'valley floor',
  'vampire cape',
  'vanilla bean',
  'vending cart',
  'video arcade',
  'video camera',
  'village well',
  'vinyl record',
  'volcanic ash',
  'voting booth',
  'waffle maker',
  'walking cane',
  'wallet chain',
  'walnut shell',
  'war memorial',
  'washer dryer',
  'washing line',
  'waste basket',
  'water bottle',
  'water heater',
  'watering can',
  'weather vane',
  'weaving loom',
  'wedding cake',
  'wedding ring',
  'wedding veil',
  'welcome sign',
  'whistle blow',
  'window blind',
  'window frame',
  'winter cabin',
  'winter frost',
  'winter scarf',
  'wishing well',
  'wood carving',
  'wooden crate',
  'wool sweater',
  'acupuncturist',
  'antelope herd',
  'antique clock',
  'apple orchard',
  'aquarium tank',
  'archery range',
  'artist studio',
  'auction gavel',
  'autumn leaves',
  'avocado toast',
  'badminton net',
  'basking shark',
  'birthday cake',
  'blueberry pie',
  'board meeting',
  'boarding pass',
  'bonfire night',
  'bonfire smoke',
  'border patrol',
  'bulldog puppy',
  'butterfly net',
  'cactus flower',
  'cactus garden',
  'camel caravan',
  'caramel apple',
  'cardboard box',
  'carnival game',
  'carousel ride',
  'cash register',
  'cat scratcher',
  'cave entrance',
  'cave explorer',
  'cave painting',
  'ceiling light',
  'chalk drawing',
  'checkout line',
  'chemistry set',
  'chimney smoke',
  'chimney sweep',
  'china cabinet',
  'chocolate bar',
  'choreographer',
  'cinnamon roll',
  'computer chip',
  'contortionist',
  'conveyor belt',
  'cookie cutter',
  'cooking class',
  'couch cushion',
  'criminologist',
  'cupboard door',
  'cupcake tower',
  'curling stone',
  'cushion cover',
  'cyclone fence',
  'dam reservoir',
  'dentist chair',
  'dermatologist',
  'desert cactus',
  'desert island',
  'desert mirage',
  'dessert table',
  'dinosaur bone',
  'diploma frame',
  'doctor office',
  'drainage pipe',
  'dream catcher',
  'elephant herd',
  'empty stadium',
  'erosion cliff',
  'exercise bike',
  'factory floor',
  'father figure',
  'fitness class',
  'flute recital',
  'flying carpet',
  'folding chair',
  'freight train',
  'frisbee catch',
  'garbage truck',
  'gasoline pump',
  'gemstone mine',
  'giant sequoia',
  'glacier crack',
  'glass ceiling',
  'goldfish bowl',
  'gps navigator',
  'graffiti wall',
  'grandpa clock',
  'grape harvest',
  'grease monkey',
  'greeting card',
  'groundhog day',
  'guitar string',
  'hamster wheel',
  'haunted house',
  'heart monitor',
  'herpetologist',
  'hieroglyphics',
  'hoedown dance',
  'horse jumping',
  'hospital gown',
  'howler monkey',
  'hunting rifle',
  'hurricane eye',
  'ichthyologist',
  'igloo builder',
  'incense stick',
  'internet cafe',
  'ironing board',
  'javelin throw',
  'jellybean jar',
  'job interview',
  'kangaroo joey',
  'karaoke night',
  'kitchen apron',
  'kite festival',
  'knight helmet',
  'komodo dragon',
  'komodo lizard',
  'leopard print',
  'leopard spots',
  'library shelf',
  'light fixture',
  'lightning rod',
  'lunar eclipse',
  'magazine rack',
  'makeup mirror',
  'mantis prayer',
  'marching band',
  'marching drum',
  'market vendor',
  'measuring cup',
  'messenger bag',
  'meteor crater',
  'meteor shower',
  'metro station',
  'military base',
  'mineral water',
  'mining helmet',
  'minnow school',
  'modeling clay',
  'monster movie',
  'monster truck',
  'moose antlers',
  'moped scooter',
  'mountain lion',
  'mudroom bench',
  'mummy costume',
  'mushroom soup',
  'napkin holder',
  'national park',
  'news reporter',
  'nurse station',
  'old fashioned',
  'origami crane',
  'paint palette',
  'pancake stack',
  'paper lantern',
  'parasol beach',
  'parking meter',
  'peach cobbler',
  'peanut butter',
  'piano recital',
  'picnic basket',
  'pirate parrot',
  'pistachio nut',
  'pitcher mound',
  'plant nursery',
  'platypus bill',
  'potion bottle',
  'printer paper',
  'protest march',
  'pumpkin spice',
  'puppet master',
  'quilt pattern',
  'radiator heat',
  'radio station',
  'rainbow color',
  'raspberry jam',
  'record player',
  'recycling bin',
  'robot factory',
  'rock climbing',
  'rocket launch',
  'rocking horse',
  'roller skates',
  'rollercoaster',
  'royal wedding',
  'ruler measure',
  'running shoes',
  'running track',
  'salmon fillet',
  'sandwich shop',
  'sausage grill',
  'savanna grass',
  'seaweed salad',
  'sheep pasture',
  'shopping mall',
  'shoulder pads',
  'slide whistle',
  'soda fountain',
  'solar eclipse',
  'space station',
  'spring shower',
  'squirrel cage',
  'stained glass',
  'street market',
  'street vendor',
  'stroller ride',
  'termite mound',
  'thatched roof',
  'theater stage',
  'thunder storm',
  'tomato garden',
  'tortilla chip',
  'train station',
  'travel agency',
  'tropical fish',
  'turbine blade',
  'tyrannosaurus',
  'vampire fangs',
  'vampire squid',
  'vending stall',
  'ventriloquist',
  'walkie talkie',
  'water balloon',
  'water buffalo',
  'water pitcher',
  'weightlifting',
  'wheat harvest',
  'windmill farm',
  'window washer',
  'winter jacket',
  'wombat burrow',
  'workout bench',
  'workshop tool',
  'wrecking ball',
  'wrestling mat',
  'zebra stripes',
  'arcade machine',
  'archery target',
  'astronaut suit',
  'athletic track',
  'backpack strap',
  'backstage pass',
  'bagpipe player',
  'balloon animal',
  'balloon vendor',
  'barbecue grill',
  'baseball glove',
  'basket weaving',
  'beach umbrella',
  'bicycle helmet',
  'billboard sign',
  'billiard table',
  'birdhouse roof',
  'birthday party',
  'blood donation',
  'bowling trophy',
  'bubble machine',
  'bucket brigade',
  'bulletin board',
  'bungalow porch',
  'cake decorator',
  'car dealership',
  'carousel horse',
  'carpet cleaner',
  'cartoon artist',
  'cathedral bell',
  'cheetah sprint',
  'chocolate chip',
  'cinnamon stick',
  'classroom desk',
  'cliffside path',
  'cocktail party',
  'coffee grinder',
  'coin collector',
  'computer mouse',
  'confetti burst',
  'crane operator',
  'croquet mallet',
  'crossing guard',
  'crosswalk sign',
  'cucumber slice',
  'dish detergent',
  'dockyard crane',
  'dominoes chain',
  'dresser drawer',
  'dresser mirror',
  'drill sergeant',
  'electric chair',
  'electric fence',
  'emergency room',
  'escalator ride',
  'eyebrow pencil',
  'factory worker',
  'family reunion',
  'farmers market',
  'feather duster',
  'ferry crossing',
  'figure skating',
  'filing cabinet',
  'fireworks show',
  'food processor',
  'fortune cookie',
  'fortune teller',
  'fountain spray',
  'french bulldog',
  'gaming console',
  'graduation cap',
  'grilled cheese',
  'hardware store',
  'helicopter pad',
  'highway patrol',
  'holiday parade',
  'honeydew melon',
  'honeymoon trip',
  'hopscotch game',
  'horseback ride',
  'humpback whale',
  'kangaroo pouch',
  'kettle whistle',
  'lacrosse stick',
  'laundry basket',
  'lawn sprinkler',
  'lemonade stand',
  'limestone cave',
  'lollipop stick',
  'lottery ticket',
  'mango smoothie',
  'martial artist',
  'mascot costume',
  'measuring tape',
  'medal ceremony',
  'medical clinic',
  'mermaid scales',
  'mermaid statue',
  'metal detector',
  'microwave oven',
  'mountain trail',
  'museum exhibit',
  'music festival',
  'native village',
  'nature reserve',
  'night watchman',
  'orchard ladder',
  'paint splatter',
  'painting easel',
  'paleontologist',
  'pancake batter',
  'paper airplane',
  'parachute jump',
  'parade balloon',
  'parking garage',
  'passport stamp',
  'peacock spider',
  'perfume bottle',
  'picnic blanket',
  'piggyback ride',
  'plastic bottle',
  'police station',
  'popcorn bucket',
  'popcorn kernel',
  'puppet theater',
  'pyramid scheme',
  'racecar driver',
  'rainbow bridge',
  'recliner chair',
  'remote control',
  'rock formation',
  'rooftop garden',
  'rowing machine',
  'salad dressing',
  'sandwich stack',
  'satellite dish',
  'school janitor',
  'security guard',
  'shooting comet',
  'shower curtain',
  'sidewalk chalk',
  'skeleton bones',
  'snowboard jump',
  'softball pitch',
  'spaghetti bowl',
  'stadium lights',
  'steering wheel',
  'strainer sieve',
  'submarine crew',
  'sumo wrestling',
  'sunroom window',
  'tangerine peel',
  'telephone wire',
  'tornado funnel',
  'treasure chest',
  'turkey feather',
  'ukulele string',
  'umbrella stand',
  'unicycle rider',
  'vacuum cleaner',
  'valentine card',
  'vegetable soup',
  'velvet curtain',
  'volleyball net',
  'vulture circle',
  'warehouse fire',
  'waterfall drop',
  'wildfire smoke',
  'wrapping paper',
  'wrestling belt',
  'yogurt parfait',
  'zebra crossing',
  'zucchini bread',
  'alligator swamp',
  'ambulance siren',
  'armadillo shell',
  'backyard garden',
  'basketball hoop',
  'bathroom mirror',
  'battery charger',
  'boomerang throw',
  'breakdance move',
  'brussels sprout',
  'cargo container',
  'catapult launch',
  'cinematographer',
  'classroom globe',
  'courtroom trial',
  'dashboard light',
  'fairy godmother',
  'family portrait',
  'flashlight beam',
  'football helmet',
  'geyser eruption',
  'gingerbread man',
  'graffiti artist',
  'graveyard shift',
  'gymnastics beam',
  'haunted mansion',
  'hedgehog spikes',
  'hidden treasure',
  'hiking backpack',
  'hydraulic press',
  'inflatable pool',
  'instrument case',
  'invisible cloak',
  'kitchen counter',
  'knitting needle',
  'lighthouse beam',
  'marathon runner',
  'masquerade ball',
  'medicine bottle',
  'medieval castle',
  'meteorite crash',
  'military parade',
  'monster costume',
  'morning routine',
  'mountain biking',
  'mushroom forest',
  'nutcracker doll',
  'ophthalmologist',
  'orchard harvest',
  'panda enclosure',
  'peacock feather',
  'penguin exhibit',
  'pinball machine',
  'pineapple slice',
  'popcorn machine',
  'pumpkin carving',
  'recycling truck',
  'referee whistle',
  'reindeer sleigh',
  'salamander tail',
  'sand volleyball',
  'shrimp cocktail',
  'skateboard ramp',
  'skylight window',
  'squirrel monkey',
  'stalactite cave',
  'stamp collector',
  'sunflower field',
  'sunglasses case',
  'tasmanian devil',
  'telephone booth',
  'theater curtain',
  'traffic officer',
  'train conductor',
  'training wheels',
  'trampoline flip',
  'trampoline park',
  'tunnel entrance',
  'underwater cave',
  'vacation resort',
  'vegetable stand',
  'vending machine',
  'wardrobe closet',
  'warehouse shelf',
  'washing machine',
  'waterproof coat',
  'wedding planner',
  'wilderness camp',
  'window shopping',
  'accordion player',
  'aircraft carrier',
  'ambulance driver',
  'anesthesiologist',
  'avalanche rescue',
  'badminton racket',
  'baseball diamond',
  'blacksmith forge',
  'botanical garden',
  'cable television',
  'children playing',
  'comic convention',
  'community garden',
  'earthquake drill',
  'earthworm tunnel',
  'electric scooter',
  'espresso machine',
  'flight simulator',
  'football stadium',
  'fraternity house',
  'garbage disposal',
  'hammerhead shark',
  'harvest festival',
  'helicopter blade',
  'koala eucalyptus',
  'landscape artist',
  'lantern festival',
  'magnifying glass',
  'marine biologist',
  'megaphone speech',
  'microphone stand',
  'mozzarella stick',
  'noise cancelling',
  'personal trainer',
  'playground slide',
  'projector screen',
  'recycling center',
  'scoreboard clock',
  'sculpture garden',
  'slingshot pebble',
  'stamp collection',
  'stepladder climb',
  'tightrope walker',
  'triceratops horn',
  'underground cave',
  'vegetable garden',
  'volcano eruption',
  'volleyball spike',
  'wildflower field',
  'chemistry teacher',
  'children hospital',
  'chocolate factory',
  'construction site',
  'envelope stuffing',
  'gingerbread house',
  'glove compartment',
  'gorilla enclosure',
  'grandfather clock',
  'greenhouse effect',
  'halloween costume',
  'hurricane shelter',
  'insect collection',
  'interior designer',
  'lighthouse island',
  'lighthouse keeper',
  'mannequin display',
  'marshmallow toast',
  'rainforest canopy',
  'sanitation worker',
  'stethoscope check',
  'university campus',
  'wheelbarrow wheel',
  'amphibious vehicle',
  'apartment building',
  'chocolate fountain',
  'crystal chandelier',
  'hologram projector',
  'university library',
  'dollhouse furniture',
  'government building',
  'stringed instrument',
  'submarine periscope',
  'private investigator',
  'strawberry shortcake',
];

// Long words for ui testing
// const DEFAULT_WORDS = [
//   'SUPERPROPORTIONALITY',
//   'AMAZING MILKSHAKE',
//   'WWWWWWWWWWWWWWWWWWWW',
//   'FLABBERGASTED PENGUIN',
//   'EXTRAORDINARY BANANA',
//   'INCREDIBLE SPACESHIP',
//   'UNBELIEVABLE GIRAFFE',
//   'ASTONISHING PINEAPPLE',
//   'MARVELOUS JELLYFISH',
//   'PHENOMENAL CHOCOLATE',
//   'STUPENDOUS ELEPHANT',
// ];

export const getWordPool = (): string[] => {
  return DEFAULT_WORDS;
};

/**
 * Fisher-Yates shuffle to pick random words from the pool
 * @param pool array of words to pick from
 * @param count count of words to pick
 * @returns Statistically random selection of words from the pool. Note that if count > pool.length,
 * it will return all words in random order without duplicates.
 */
export const pickRandomWords = (pool: string[], count: number): string[] => {
  const shuffled = [...pool]; //shallow copy

  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));

    [shuffled[i], shuffled[j]] = [shuffled[j] as string, shuffled[i] as string];
  }
  return shuffled.slice(0, count);
};

//Normalize string for safe comparison by trimming whitespace and converting to lowercase
const normalize = (word: string): string => word.toLowerCase().trim();

/**
 * Filters out words that have been recently used (uses Set for o(1) lookup)
 * @param pool The pool of words to filter
 * @param usedWords An array of words that have been used recently
 * @returns Filtered pool with recently used words removed. Comparison is done in a case-insensitive manner and
 * ignores leading/trailing whitespace to prevent accidental repeats due to formatting differences.
 */
export const filterRecentlyUsedWords = (pool: string[], usedWords: string[]): string[] => {
  const normalizedUsed = new Set(usedWords.map(normalize));
  return pool.filter((word) => !normalizedUsed.has(normalize(word)));
};

/**
 * Gets the available word pool by filtering out recently used words from the full pool. If the resulting pool is
 * too small to provide enough choices, it falls back to the full pool to ensure the game can continue without
 * interruption.
 * @param fullPool The complete pool of words
 * @param usedWords An array of words that have been used recently
 * @returns An array of words that can be used for the current round, with recently used words filtered out
 * when possible to enhance game variety.
 */
export const getAvailableWordPool = (fullPool: string[], usedWords: string[]): string[] => {
  const filteredPool = filterRecentlyUsedWords(fullPool, usedWords);

  //Failsafe: If filtering results in an empty pool (which can happen if the pool is small and many rounds
  // have been played), return the full pool to avoid game-breaking scenarios
  if (filteredPool.length < GAME_CONSTANTS.WORD_CHOICES_COUNT) {
    return fullPool;
  }
  return filteredPool;
};

/**
 * A single word pool that handles both custom and default words, prioritizing custom words when available.
 * It first checks for default scenario where there are no custom words so it just returns the default pool
 * filtered for recently used words.
 * In case custom words are available, it first attempts to use custom words, filtering out recently used ones.
 * If there are not enough custom words available, it fills the remaining slots with default words,
 * also ensuring that recently used default words and overlapping custom and default words are excluded.
 * It also works in strict mode where only custom words are used, allowing repeats if the custom pool is exhausted.
 * @param customWords The array of custom words
 * @param usedWords An array of words that have been used recently
 * @param customWordsOnly A flag indicating whether to use only custom words
 * @returns A set of words for the current round depending on the scenario
 */
export const getWordPoolWithCustomPriority = (
  customWords: string[] | undefined,
  usedWords: string[],
  customWordsOnly: boolean,
): string[] => {
  const defaultPool = getWordPool();

  //1. No custom words at all -> use default pool
  if (!customWords || customWords.length === 0) {
    return getAvailableWordPool(defaultPool, usedWords);
  }

  //Filter out recently used words from the custom pool
  const availableCustom = filterRecentlyUsedWords(customWords, usedWords);

  //2. STRICT MODE: Only custom words. If exhausted, we will allow repeats to respect the user input of strict mode.
  if (customWordsOnly) {
    return availableCustom.length >= GAME_CONSTANTS.WORD_CHOICES_COUNT
      ? availableCustom
      : customWords; // Allow repeats if the pool is exhausted
  }

  //3. HYBRID MODE (Strict Priority Fill)
  //First we grab as many unused custom words as we can (up to the required 3)
  const amountToTake = Math.min(availableCustom.length, GAME_CONSTANTS.WORD_CHOICES_COUNT);
  const customToUse = pickRandomWords(availableCustom, amountToTake);

  //If we grabbed fewer than 3 words (because the custom pool is small or exhausted), we calculate the deficit
  //and fill the rest with default words ensuring that we don't repeat recently used words from the default pool either.
  if (customToUse.length < GAME_CONSTANTS.WORD_CHOICES_COUNT) {
    const deficit = GAME_CONSTANTS.WORD_CHOICES_COUNT - customToUse.length;

    //Combine used words and already selected custom words to avoid repeats
    //This prevents the scenario where both custom and default pools have overlapping words and
    //we have selected the overlapping word from the custom pool, for this round and hence we
    //don't have it in usedWords yet, but we don't want to select it again from the default pool.
    const exclusionList = [...usedWords, ...customToUse];

    const availableDefaults = filterRecentlyUsedWords(defaultPool, exclusionList);
    const defaultsToUse = pickRandomWords(availableDefaults, deficit);

    //Return the 3 words needed
    return [...customToUse, ...defaultsToUse];
  }

  // If we had enough custom words to fill all 3 choices, just return them!
  return customToUse;
};
