name: Deploy to Production

on:
  push:
    branches:
      - main # This triggers the workflow only when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute Deployment Commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/scribblitz
            git pull origin main
            docker compose -f docker-compose.prod.yml up --build -d --remove-orphans